name: 'Semiconductor_news_manual'

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3 
    - name: Set up Python 3.8
      uses: actions/setup-python@v3 
      with:
        python-version: "3.8"
    - name: Install dependencies 
      run: | 
        python -m pip install --upgrade pip 
        pip install ccxt 
        pip install pandas
        pip install python-telegram-bot==20.3
        pip install bs4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run 
      run: | 
        python final1.py
